export { ApiError, toApiError } from './error'
export { httpClient, unwrapCollection, unwrapData } from './client'
export { authService } from './resources/authService'
export { patientAuthService } from './resources/patientAuthService'
export { specialtiesService } from './resources/specialtiesService'
export { insurancesService } from './resources/insurancesService'
export { doctorsService } from './resources/doctorsService'
export { secretariesService } from './resources/secretariesService'
export { slotsService } from './resources/slotsService'
export { appointmentsService } from './resources/appointmentsService'
export { paymentsService } from './resources/paymentsService'
export { notificationsService } from './resources/notificationsService'
export { newsService } from './resources/newsService'

